version: "3"
services:
  redis:
    container_name: redis
    image: redis:7.0.10-alpine
    volumes:
      - ./docker/redis:/usr/local/etc/redis
    ports:
      - "6379:6379"
  rls:
    container_name: rls
    image: localhost/rls:latest
    ports:
      - "80:80"
